# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: orch-ui-root
description: Deploy Edge Orchestrator UI pods on Kubernetes
type: application
version: 4.0.0-dev
# Default appVersion will be overwritten by a the build to use the version from package.json.

# This value is supplied only to enable local unbuilt deployment of released content.
appVersion: "4.0.0-dev"
annotations: {}
dependencies: []
