# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: orch-ui-infra
description: Deploy the Edge-Native Software Platform Infrastructure pod
type: application
version: 4.0.0
# Default appVersion will be overwritten by a the build to use the version from package.json.

appVersion: "4.0.0"
dependencies: []
annotations: {}
